# Generated by Django 2.2 on 2020-02-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200217_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'This email has already been used.'}, max_length=192, verbose_name='邮箱'),
        ),
    ]
