# Generated by Django 2.2 on 2020-02-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200217_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='motto',
            field=models.CharField(blank=True, max_length=192, verbose_name='警句'),
        ),
    ]
