# Generated by Django 2.2 on 2020-02-15 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=192, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('access_level', models.PositiveIntegerField(choices=[(0, '仅课程管理员可见'), (10, '仅受邀用户可见'), (20, '公开')], default=0, verbose_name='访问控制')),
                ('assignments', models.ManyToManyField(related_name='course_assignment', to='assignment.Assignment')),
                ('assistants', models.ManyToManyField(related_name='course_assistants', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='course_participants', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(related_name='course_teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
