# Generated by Django 2.2 on 2020-02-17 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assignments',
            field=models.ManyToManyField(null=True, related_name='course_assignment', to='assignment.Assignment'),
        ),
        migrations.AlterField(
            model_name='course',
            name='assistants',
            field=models.ManyToManyField(null=True, related_name='course_assistants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='course_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CourseInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'unique_together': {('course', 'code')},
            },
        ),
    ]
