# Generated by Django 2.2 on 2020-02-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200217_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='assignments',
            field=models.ManyToManyField(blank=True, related_name='course_assignments', to='assignment.Assignment'),
        ),
    ]
