# Generated by Django 2.2 on 2020-02-15 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(-1, 'Submitted'), (0, 'Accepted'), (1, 'Rejected')], db_index=True, default=-1)),
                ('score', models.IntegerField(default=100)),
                ('pdf_submit', models.FileField(blank=True, null=True, upload_to='pdf/%Y%m%d/', verbose_name='提交pdf')),
                ('pdf_feedback', models.FileField(blank=True, null=True, upload_to='pdf/%Y%m%d/', verbose_name='反馈pdf')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.Assignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
