# Generated by Django 2.2 on 2020-02-19 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submission', '0002_auto_20200216_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='pdf_feedback',
            new_name='feedback_pdf',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='score',
            new_name='feedback_score',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='author',
            new_name='submit_author',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='pdf_submit',
            new_name='submit_pdf',
        ),
        migrations.AddField(
            model_name='submission',
            name='feedback_auther',
            field=models.ManyToManyField(related_name='submission_feedback_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='feedback_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='submit_content',
            field=models.TextField(blank=True),
        ),
    ]
