# -*-coding:utf-8 -*-
"""
Django settings for sortask project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!lmeg!7yx8a5f_g%p6w3**+9!s*8d*b$4xspx*b-k&gkbeftc0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # my
    'home.apps.HomeConfig',
    'account.apps.AccountConfig',
    'assignment.apps.AssignmentConfig',
    'course.apps.CourseConfig',
    'submission.apps.SubmissionConfig',
    'polygon.apps.PolygonConfig',

    # third party
    'phonenumber_field',
    'captcha',
    'imagekit',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sortask.urls'

TEMPLATES = [
    # {
    #     'BACKEND': 'django.template.backends.jinja2.Jinja2',
    #     'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'sortask/templates')],
    #     'APP_DIRS': True,
    #     'OPTIONS': {
    #         'context_processors': [
    #             'django.template.context_processors.debug',
    #             'django.template.context_processors.request',
    #             'django.contrib.auth.context_processors.auth',
    #             'django.contrib.messages.context_processors.messages',
    #         ],
    #         'environment': 'sortask.jinja2_env.environment',
    #     },
    # },
    {
        'BACKEND': 'django_jinja.backend.Jinja2',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'polygon/templates')],
        # 'OPTIONS': {'environment': 'eoj3.jinja2.environment'},
        'APP_DIRS': True,
        'OPTIONS': {
            "undefined": None,
            "match_extension": ".jinja2",
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "django.template.context_processors.i18n",
            ],
            "globals": {
                # "myGlobal": "utils.jinja2.globals.is_active",
                # "myGlobal2": "utils.jinja2.globals.paginator",
                "myGlobal3": "utils.jinja2.globals.render_field",
                # "myGlobal4": "utils.jinja2.globals.url_replace",
                # "myGlobal5": "utils.jinja2.globals.static_file_modify",
                # "myGlobal6": "utils.jinja2.globals.render_comment_tree",
                # "myGlobal7": "utils.jinja2.globals.url_encode",
                # "myGlobal8": "utils.jinja2.globals.username_display",
                # "myGlobal9": "utils.jinja2.globals.get_current_language",
            },
            "extensions": [
                "jinja2.ext.do",
                "jinja2.ext.loopcontrols",
                "jinja2.ext.with_",
                "jinja2.ext.i18n",
                "jinja2.ext.autoescape",
                "django_jinja.builtins.extensions.CsrfExtension",
                "django_jinja.builtins.extensions.CacheExtension",
                "django_jinja.builtins.extensions.TimezoneExtension",
                "django_jinja.builtins.extensions.UrlsExtension",
                "django_jinja.builtins.extensions.StaticFilesExtension",
                "django_jinja.builtins.extensions.DjangoFiltersExtension",
            ],
            "translation_engine": "django.utils.translation",
        },
    },
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), os.path.join(BASE_DIR, 'learning_logs/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sortask.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': '/opt/shizuoye/config/mysql.cnf',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/


EFAULT_CHARSET = 'UTF-8'
LANGUAGE_CODE = 'zh-Hans'
LANGUAGES = (
  ('zh-Hans', '简体中文'),
)

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = 'static'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]



AUTH_USER_MODEL = 'account.User'

LOGIN_REDIRECT_URL = '/'
# login_required redirect to this
LOGIN_URL = '/account/login/'

# CAPTCHA
CAPTCHA_FOREGROUND_COLOR = "#000000"
CAPTCHA_FILTER_FUNCTIONS = []
CAPTCHA_CHALLENGE_FUNCT = 'sortask.captcha.random_math_challenge'

# media files: avatar, image, pdf

MEDIA_ROOT = os.path.join(BASE_DIR.replace('sortask', ''), 'media')
MEDIA_URL = '/media/'

# email
# change into config files
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.163.com'  # SMTP服务器地址
EMAIL_PORT = 465
EMAIL_HOST_USER = 'shizuoye_service@163.com'
EMAIL_HOST_PASSWORD = 'Cr1xxMzM9KmcXdbq'
EMAIL_FROM = 'shizuoye_service@163.com'
DEFAULT_FROM_EMAIL = 'shizuoye_service@163.com'