# Generated by Django 2.2 on 2020-02-17 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_assignment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
